---
- hosts: all
  become: yes
  tasks:
    - name: Pull the Docker image
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Run the Docker container
      docker_container:
        name: app
        image: "{{ image_name }}:{{ image_tag }}"
        ports:
          - "80:5000"
        state: started
        restart_policy: always
